Fixing values of UA.disconnected event (#701)
this.ondisconnect() function calls Transport._onDisconnect() but this
function accept three arguments: error, code and reason. Not single data
object.

This causes that UA.disconnected event instead of having 4 simple
fields: socket, error, code and reason contain following object:
{
    socket: <socket instance>
    error: {
        socket: <socket instance>,
        error:  <valid data>,
        code:   <valid data>,
        reason: <valid data>
    },
    code: undefined,
    reason: undefined
}